language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
# - pip install travis-wait-improved
# - install travis_wait
script:
- export ALPHA_KEY=$ALPHA_KEY
- python .travis/data.py
# - travis-wait-improved --timeout 15m .travis/make.py
# - travis_wait 480 python .travis/make.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master